//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCBaseProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUserCompany
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public int CompanyID { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual SysCompany SysCompany { get; set; }
        public virtual SysUser SysUser { get; set; }
    }
}
